### ISSUE TITLE
As a reader of the CoC, I want an introduction with stated purpose.

### ISSUE THREAD

**Issue by dac514** [derickr/php-code-of-conduct#22]
I think the CoC should start with a stated goal. Something like:

> PHP is a widely-used open source general-purpose scripting language that is especially suited for web development. It is used by millions of developers world wide, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality. As project maintainers we are committed to making participation in this project a comfortable experience for everyone,

**Comment by ramsey** [comment]
I like it.

**Comment by derickr** [comment]
I like it too, but it should go into the introduction at https://github.com/derickr/php-community-health/blob/master/RFC.rst — would you want to make a PR please?

**Comment by dac514** [comment]
Ok. 

@see https://github.com/derickr/php-community-health/pull/29

**Comment by derickr** [comment]
I've merged #29, so closing this one.
